# Generated by Django 4.2 on 2023-05-01 07:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('instagram', models.CharField(blank=True, max_length=128)),
                ('telegram', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('website', models.CharField(blank=True, max_length=128)),
                ('services_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_cards.servicestype')),
            ],
        ),
    ]
