# Generated by Django 4.2 on 2023-05-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_cards', '0002_businesscard_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscard',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
